image: java:openjdk-8

stages:
  - test
  - deploy

before_script:
  - apt-get update -y
  - apt-get install gradle -y

test_async:
  stage: test
  script:
   - gradle test --info
  tags:
    - docker

staging:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - deploy
  tags:
    - docker
